# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Configuring environment
        run: ssh-add - <<< ${{secrets.WEB_LIBRARIES_PRIVATE_KEY}}
 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run:  |
          cd echarts-viewer
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          fi
      - run: |
          cd echarts-viewer
          npm run build --if-present
  deploy:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@develop
       - name: Web deployment
         run: |
          ssh-add - <<< ${secrets.WEB_REPOSITORY_PRIVATE_KEY}
          git clone https://github.com/BioBam/omicsboxweb-amplify.git
          
